[package]
name = "aoc-2024-rust"
version = "0.1.0"
authors = ["Guillermo Galan <mail@guillego.com>"]
edition = "2021"

[lib]
bench = false

[dependencies]
rust-crypto = "0.2.36"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
